require('dotenv').config(); // Load environment variables from .env file
const express = require('express');
const crypto = require('crypto'); // For Provably Fair RNG
const redis = require('redis'); // Import the redis library
const morgan = require('morgan'); // Import the HTTP request logger

const app = express();
const PORT = process.env.PORT || 3000;

// --- Middleware Setup ---
app.use(express.json());
app.use(express.static('public')); // Serve static files from the 'public' directory
app.use(morgan('dev')); // Use morgan for logging requests to the console

// --- Redis Client Setup ---
const redisClient = redis.createClient({
    url: process.env.REDIS_URL
});

// --- Game Constants ---
// These represent the locked PAR sheet for the game.
const GAME_CONSTANTS = {
    STEP_1: {
        WIN_PROBABILITY: 0.4825, // 48.25%
        PAYOUT_MULTIPLIER: 2.00,
    },
    STEP_2_TIERS: [
        { name: 'Mythic', probability: 0.0001, multiplier: 1000.00 }, // 0.01%
        { name: 'Legendary', probability: 0.0010, multiplier: 100.00 }, // 0.10%
        { name: 'Epic', probability: 0.0400, multiplier: 10.00 },   // 4.00%
        { name: 'Uncommon', probability: 0.4000, multiplier: 3.50 },    // 40.00%
        // The remaining 55.89% is the Bust outcome
    ],
};

/*
DEPRECATED: The in-memory store is now replaced by Redis.
const activeRounds = {};
*/
const ROUND_EXPIRATION_SECONDS = 600; // Rounds expire after 10 minutes

/**
 * Provably Fair RNG function.
 * Generates a deterministic float between 0 and 1 based on the inputs.
 * @param {string} serverSeed - The secret seed generated by the server.
 * @param {string} clientSeed - The public seed provided by the client.
 * @param {number} nonce - A number that is incremented for each roll in a round.
 * @returns {number} A float between 0 and 1.
 */
const getProvablyFairResult = (serverSeed, clientSeed, nonce) => {
    // Create an HMAC (Hash-based Message Authentication Code) using SHA256
    const hmac = crypto.createHmac('sha256', serverSeed);
    // Update the HMAC with the client seed and nonce
    const hash = hmac.update(`${clientSeed}-${nonce}`).digest('hex');

    // We'll use the first 8 characters of the hex hash for our roll
    const subHash = hash.substring(0, 8);
    const decimalValue = parseInt(subHash, 16);

    // Normalize the decimal value to a float between 0 and 1
    // 0xFFFFFFFF is the maximum value for an 8-character hex string
    return decimalValue / 0xFFFFFFFF;
};

/**
 * @route POST /api/bet
 * @description Initiates a new game round. Deducts the bet amount, pre-generates the full game path (Step 1 and Step 2), and returns the Step 1 outcome.
 * @param {object} req.body - The request body.
 * @param {string} req.body.clientSeed - A public seed provided by the client for provably fair generation.
 * @param {number} req.body.betAmount - The amount to wager for the round.
 * @param {number} req.body.balance - The player's current balance before the bet.
 * @returns {object} 200 - On success, returns the round ID and Step 1 outcome.
 */
app.post('/api/bet', async (req, res, next) => { // Add 'next' for error handling
    try {
        // For this MVP, we'll assume clientSeed, betAmount, and balance are in the request body.
        const { clientSeed, betAmount, balance } = req.body;

        if (!clientSeed || !betAmount || balance === undefined) {
            return res.status(400).json({ error: "clientSeed, betAmount, and balance are required." });
        }

        // 1. Generate server-side secrets for this round
        const serverSeed = crypto.randomBytes(32).toString('hex');
        const roundId = `req_${crypto.randomBytes(12).toString('hex')}`;

        // --- Step 1: Determine initial win/loss ---
        const step1Roll = module.exports.getProvablyFairResult(serverSeed, clientSeed, 0); // Nonce 0 for Step 1
        const isStep1Win = step1Roll < GAME_CONSTANTS.STEP_1.WIN_PROBABILITY;

        // --- Step 2: Pre-generate the double-down outcome regardless of Step 1 result ---
        const step2Roll = module.exports.getProvablyFairResult(serverSeed, clientSeed, 1); // Nonce 1 for Step 2
        let cumulativeProb = 0;
        let step2Outcome = { name: 'Bust', multiplier: 0 }; // Default to Bust

        for (const tier of GAME_CONSTANTS.STEP_2_TIERS) {
            cumulativeProb += tier.probability;
            if (step2Roll < cumulativeProb) {
                step2Outcome = { name: tier.name, multiplier: tier.multiplier };
                break;
            }
        }

        // 2. Store the full pre-generated path in Redis
        const roundData = {
            serverSeed, // Stored to be revealed later for verification
            clientSeed,
            betAmount,
            step1Outcome: isStep1Win ? 'win' : 'lose',
            step2Outcome, // Contains { name, multiplier }
        };
        // Use SET with EX to automatically expire the round data
        await redisClient.set(roundId, JSON.stringify(roundData), {
            EX: ROUND_EXPIRATION_SECONDS,
        });

        // 3. Construct and send the response based on Step 1 outcome
        const newBalance = balance - betAmount;
        if (!isStep1Win) {
            // If the player loses Step 1, the round is over. Clean up immediately.
            await redisClient.del(roundId);
            return res.json({
                round_id: roundId,
                step_1_outcome: "lose",
                current_multiplier: 0.00,
                balance: newBalance,
            });
        }

        res.json({
            round_id: roundId,
            step_1_outcome: "win",
            current_multiplier: GAME_CONSTANTS.STEP_1.PAYOUT_MULTIPLIER,
            balance: newBalance,
        });
    } catch (error) {
        next(error); // Pass any errors to the global error handler
    }
});

/**
 * Middleware to find and validate an active round.
 * Attaches round data to the request object if found.
 */
const findActiveRound = async (req, res, next) => {
    const { round_id, balance } = req.body;

    if (!round_id || balance === undefined) {
        return res.status(400).json({ error: "round_id and balance are required." });
    }

    try {
        const roundDataString = await redisClient.get(round_id);
        if (!roundDataString) {
            return res.status(404).json({ error: "Round not found or has already been completed." });
        }

        // Attach the parsed data to the request object for the next handler
        req.roundData = JSON.parse(roundDataString);
        next(); // Proceed to the main route handler
    } catch (error) {
        next(error);
    }
};

/**
 * @route POST /api/cashout
 * @description Executes the "cash out" action for an active round, awarding the 2.00x Step 1 win.
 * @param {object} req.body - The request body.
 * @param {string} req.body.round_id - The ID of the active round to cash out.
 * @param {number} req.body.balance - The player's current balance before this action.
 * @returns {object} 200 - On success, returns a confirmation and the amount won.
 * @returns {object} 404 - If the round_id is not found or already completed.
 */
app.post('/api/doubledown', findActiveRound, async (req, res, next) => {
    try {
        // The roundData is already attached to req by the findActiveRound middleware
        const { roundData } = req;
        const { round_id, balance } = req.body;

        // 1. Retrieve the pre-generated outcome
        const { step2Outcome, betAmount } = roundData;
        const amountWon = betAmount * step2Outcome.multiplier;
        const newBalance = balance + amountWon;

        // 2. Clean up the completed round from Redis
        await redisClient.del(round_id);

        // 3. Send the final response
        res.json({
            round_id: round_id,
            step_2_tier: step2Outcome.name,
            final_multiplier: step2Outcome.multiplier,
            amount_won: amountWon,
            balance: newBalance,
        });
    } catch (error) {
        next(error);
    }
});

/**
 * @route POST /api/cashout
 * @description Executes the "cash out" action for an active round, awarding the 2.00x Step 1 win.
 * @param {object} req.body - The request body.
 * @param {string} req.body.round_id - The ID of the active round to cash out.
 * @param {number} req.body.balance - The player's current balance before this action.
 * @returns {object} 200 - On success, returns a confirmation and the amount won.
 * @returns {object} 404 - If the round_id is not found or already completed.
 */
app.post('/api/cashout', findActiveRound, async (req, res, next) => {
    try {
        const { roundData } = req;
        const { round_id, balance } = req.body;

        // 1. Calculate the cashout amount (always 2.00x the base bet)
        const amountWon = roundData.betAmount * GAME_CONSTANTS.STEP_1.PAYOUT_MULTIPLIER;
        const newBalance = balance + amountWon;

        // 2. Clean up the completed round from Redis
        await redisClient.del(round_id);

        // 3. Send the final response
        res.json({
            message: "Cashed out successfully",
            amount_won: amountWon,
            balance: newBalance,
        });
    } catch (error) {
        next(error);
    }
});

// --- Global Error Handler ---
// This must be the LAST middleware added.
app.use((err, req, res, next) => {
    console.error(err.stack); // Log the error for debugging
    res.status(500).json({ error: 'Internal Server Error' });
});

const startServer = async () => {
    try {
        await redisClient.connect();
        console.log('Connected to Redis...');

        const server = app.listen(PORT, '0.0.0.0', () => {
            console.log(`Server running. Access it from this machine at: http://localhost:${PORT}`);
            console.log('To access from other devices on the same network, find your local IP address.');
        });
        return server; // Return the server instance
    } catch (err) {
        console.error('Failed to start server:', err);
        process.exit(1);
    }
};

// Only start the server if this file is run directly
if (require.main === module) {
    startServer();
}

// Export for testing purposes
module.exports = { app, startServer, redisClient, getProvablyFairResult };
